### PR TITLE
Circuit and VM Reports

### PR DESCRIPTION
**Pull request by tyler-8**
A handful of reports for checking circuit/site counts and VM/cluster/site counts.

### CODE REVIEW

**Comment by mmahacek** [comment]
I would suggest adding some comments to the top of any files that rely on custom fields or tags.  A little longer comment at the top of the reports may help people determine if the report would be applicable to their needs.

Thanks for sharing these!

**Comment by tyler-8** [comment]
There are docstrings for the relevant report classes as not every report requires anything custom. Hopefully these are just used as starting points to see the capabilities rather than drop-in ready (though maybe there is a way we can standardize on what's drop-in ready vs customization require).

**Comment by mmahacek** [comment]
The decommission fields were the main ones I was suggesting including the documentation.  👍

**Comment by mmahacek** [comment]
I don't have your custom fields or tags deployed on my server, but otherwise the reports look to run as expected. I definitely see adapting some of these for our use.

**Pull request merged**
